RENAME TABLE `datisimulazione` TO `analysis_result`;

ALTER TABLE `analysis_result`
	CHANGE COLUMN `a` `a` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `oraAnalisi`,
	CHANGE COLUMN `b` `b` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `a`,
	CHANGE COLUMN `c` `c` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `b`,
	CHANGE COLUMN `d` `d` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `c`,
	CHANGE COLUMN `Td` `Td` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `d`,
	CHANGE COLUMN `Cs0` `Cs0` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `Td`,
	CHANGE COLUMN `Cc0` `Cc0` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `Cs0`,
	CHANGE COLUMN `Kc0` `Kc0` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `Cc0`,
	CHANGE COLUMN `t` `t` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `Kc0`,
	CHANGE COLUMN `FPV` `FPV` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `t`,
	CHANGE COLUMN `FPT` `FPT` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `FPV`,
	CHANGE COLUMN `SPV` `SPV` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `FPT`,
	CHANGE COLUMN `SPT` `SPT` DOUBLE(10,5) NOT NULL DEFAULT 0 AFTER `SPV`;

CREATE TABLE `analysis_params` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`a_lb` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`b_lb` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`td_lb` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cs0_lb` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cc0_lb` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`a_ub` DOUBLE(10,3) NULL DEFAULT NULL,
	`b_ub` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`td_ub` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cs0_ub` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cc0_ub` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`a_init` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`b_init` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`td_init` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cs0_init` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cc0_init` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`iterations` INT(10) UNSIGNED NULL DEFAULT NULL,
	`a_fixed` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`b_fixed` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`td_fixed` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cs0_fixed` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`cc0_fixed` DOUBLE(10,3) UNSIGNED NULL DEFAULT NULL,
	`global_alg` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`local_alg` VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`time` DOUBLE(10,5) UNSIGNED NULL DEFAULT NULL,
	`id_result` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `id_UNIQUE` (`id`) USING BTREE,
	INDEX `param_result_idx` (`id_result`) USING BTREE,
	CONSTRAINT `param_result` FOREIGN KEY (`id_result`) REFERENCES `analysis_result` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE
)
COMMENT='Params used to perform analysis'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;



